import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createSession,startRound,markSeen,openVote,castVote,revealFor,ranking,defaults,roundHasImages,replaceUnillustratedRound,type Session} from '../lib/game/engine.ts';
import {characters,playableCharacters,playablePairs,hasVerifiedImage} from '../lib/game/catalog.ts';
import {createRoom,joinRoom,actRoom,roomView,transferHost} from '../lib/game/room.ts';
function ready(n=4,impostors=1):Session{let s=startRound(createSession(Array.from({length:n},(_,i)=>`P${i}`),{...defaults,impostors}));for(const p of s.players)s=markSeen(s,p.id);return s;}
function voting(n=4):Session{const s=ready(n);s.round!.impostors=[s.players[0].id];return openVote(s);}
function ballot(s:Session,targets:number[]){for(let i=0;i<targets.length;i++)s=castVote(s,s.players[i].id,s.players[targets[i]].id);return s;}
test('original catalogue IDs survive expansion without duplicates',()=>{assert.ok(characters.length>=176);assert.equal(new Set(characters.map(c=>c.id)).size,characters.length);for(let g=0;g<19;g++)for(let i=0;i<4;i++)assert.ok(characters.some(c=>c.id===`c${g}-${i}`));assert.equal(characters.find(c=>c.id==='c0-0')?.character_name,'Walter White');assert.equal(characters.find(c=>c.id==='c18-3')?.character_name,'Miss Marple');});

test('all 100 added identities have images and pairs at every difficulty',()=>{const added=characters.filter(c=>Number(c.id.split('-')[0].slice(1))>=19);assert.equal(added.length,100);for(const c of added){assert.ok(hasVerifiedImage(c),c.character_name);assert.ok(playablePairs.some(p=>p.a===c.id||p.b===c.id));for(const d of ['easy','medium','hard'])assert.ok(playablePairs.some(p=>p.difficulty===d&&(p.a===c.id||p.b===c.id)),`${c.work_name}: ${d}`);}});
test('only verified images enter playable pairs',()=>{assert.ok(playablePairs.length>0);for(const p of playablePairs)for(const id of [p.a,p.b])assert.ok(hasVerifiedImage(characters.find(c=>c.id===id)!));});
test('different mode gives one other identity without exposing a role flag',()=>{const s=ready();const imp=s.round!.impostors[0];const view=revealFor(s,imp);assert.equal(view.characterId,s.round!.alternate);assert.equal(view.isBlank,false);assert.deepEqual(Object.keys(view).sort(),['characterId','isBlank']);for(const p of s.players.filter(p=>p.id!==imp))assert.equal(revealFor(s,p.id).characterId,s.round!.main);});
test('blank mode has no character for impostor',()=>{const s=ready();s.config.mode='blank';assert.deepEqual(revealFor(s,s.round!.impostors[0]),{characterId:null,isBlank:true});});
test('missing image themes cannot be launched',()=>assert.throws(()=>startRound(createSession(['A','B','C'],{...defaults,themes:['Breaking Bad']})),/images vérifiées/));
test('all difficulties deal only illustrated cards',()=>{for(const difficulty of ['easy','medium','hard'] as const)for(let i=0;i<100;i++){const s=startRound(createSession(['A','B','C'],{...defaults,difficulty}));assert.ok(roundHasImages(s));assert.notEqual(s.round!.main,s.round!.alternate);}});
test('self vote and duplicate vote rejected',()=>{let s=voting();assert.throws(()=>castVote(s,s.players[0].id,s.players[0].id),/invalide/);s=castVote(s,s.players[0].id,s.players[1].id);assert.throws(()=>castVote(s,s.players[0].id,s.players[2].id),/déjà/);});
test('unanimous innocent votes award 100, not 150; impostor vote excluded',()=>{const s=ballot(voting(),[1,0,0,0]);assert.equal(s.round!.winner,'innocents');assert.deepEqual(s.players.map(p=>p.points),[0,100,100,100]);});
test('nonunanimous correct innocent votes award 50',()=>{const s=ballot(voting(),[1,0,0,1]);assert.equal(s.round!.winner,null);assert.deepEqual(Object.values(s.round!.voteAwards),[50,50]);assert.equal(s.players[0].points,0);});
test('impostor victory with a vote awards 150 only',()=>{const s=ballot(voting(3),[1,0,1]);assert.equal(s.round!.winner,'impostors');assert.equal(s.players[0].points,150);assert.equal(s.players[1].points,50);});
test('impostor victory without any votes awards 250 only',()=>{const s=ballot(voting(3),[1,2,1]);assert.equal(s.players[0].points,250);assert.notEqual(s.players[0].points,400);});
test('tie eliminates nobody and opens discussion',()=>{const s=ballot(voting(),[1,0,3,2]);assert.equal(s.round!.tied,true);assert.equal(s.round!.phase,'discussion');assert.deepEqual(s.round!.eliminated,[]);});
test('session points survive a new round and settings',()=>{const first=ballot(voting(),[1,0,0,0]);const next=startRound({...first,config:{...first.config,difficulty:'hard'}});assert.deepEqual(next.players.map(p=>p.points),first.players.map(p=>p.points));assert.equal(next.history.length,1);assert.equal(next.round!.number,2);});
test('ranking uses competition ranks for ties',()=>{const s=ready();s.players.forEach((p,i)=>p.points=[100,100,50,0][i]);assert.deepEqual(ranking(s).map(p=>p.rank),[1,1,3,4]);});
test('rotation prioritizes lowest impostor count',()=>{const s=ready();s.round!.phase='result';s.players.forEach((p,i)=>p.impostorCount=i===2?0:5);assert.equal(startRound(s).round!.impostors[0],s.players[2].id);});
test('unused pairs are preferred when available',()=>{const s=ready();const first=[s.round!.main,s.round!.alternate].sort().join(':');s.round!.phase='result';const next=startRound(s);assert.notEqual([next.round!.main,next.round!.alternate].sort().join(':'),first);});
test('legacy missing-image round is replaced only explicitly and points retained',()=>{const s=ready();s.round!.main='c0-0';s.players[1].points=200;assert.equal(roundHasImages(s),false);const next=replaceUnillustratedRound(s);assert.equal(next.players[1].points,200);assert.equal(next.history.length,1);assert.ok(roundHasImages(next));});
test('multiple impostors: votes for either impostor count toward unanimous 100',()=>{let s=ready(5,2);s.round!.impostors=[s.players[0].id,s.players[1].id];s=openVote(s);s=ballot(s,[2,2,0,1,0]);for(const p of s.players.slice(2))assert.equal(s.round!.voteAwards[p.id],100);});
test('3 impostors are rejected for 6 players',()=>assert.throws(()=>createSession(['a','b','c','d','e','f'],{...defaults,impostors:3})));
test('room projections never leak other assignments, scores or vote history mid-round',()=>{const r=createRoom('ABCDEF','a','A',100);joinRoom(r,'b','B',101);joinRoom(r,'c','C',102);for(const id of ['a','b','c'])actRoom(r,id,{type:'ready'},103);actRoom(r,'a',{type:'start'},104);const v=roomView(r,'b',105);assert.equal(v.round!.result,null);assert.equal('impostors' in v.round!,false);assert.equal('main' in v.round!,false);assert.equal('impostorCount' in v.players[0],false);assert.equal('currentVotes' in v.round!,false);assert.ok(playableCharacters.some(c=>c.id===v.round!.secret.characterId));assert.throws(()=>roomView(r,'outsider'),/refusé/);});
test('only host can start and configure the room',()=>{const r=createRoom('ABCDEF','a','A');joinRoom(r,'b','B');assert.throws(()=>actRoom(r,'b',{type:'start'}),/hôte/);assert.throws(()=>actRoom(r,'b',{type:'configure',config:defaults}),/hôte/);});
test('reconnect preserves assignment and points',()=>{const r=createRoom('ABCDEF','a','A',100);joinRoom(r,'b','B',101);joinRoom(r,'c','C',102);for(const id of ['a','b','c'])actRoom(r,id,{type:'ready'},103);actRoom(r,'a',{type:'start'},104);const before=roomView(r,'b',105);joinRoom(r,'b','B',200);const after=roomView(r,'b',201);assert.deepEqual(after.round!.secret,before.round!.secret);assert.deepEqual(after.players,before.players);});
test('host transfers to oldest connected remaining member',()=>{const r=createRoom('ABCDEF','a','A',100);joinRoom(r,'b','B',200);joinRoom(r,'c','C',300);actRoom(r,'a',{type:'leave'},400);assert.equal(r.host,'b');r.members.find(m=>m.id==='b')!.lastSeen=0;r.members.find(m=>m.id==='c')!.lastSeen=50000;transferHost(r,50001);assert.equal(r.host,'c');});
test('chat enforces basic anti-spam',()=>{const r=createRoom('ABCDEF','a','A',100);actRoom(r,'a',{type:'message',text:'Bonjour'},200);assert.throws(()=>actRoom(r,'a',{type:'message',text:'Encore'},300),/message à la fois/);});
