'use client';
import { useEffect, useState } from 'react';
import { Fingerprint, Smartphone, Globe2, BookOpen, X, ArrowLeft, Users, ShieldCheck, Trophy, Settings, Sparkles } from 'lucide-react';
import { Setup } from '@/components/game/Setup';
import { LocalGame, Recap } from '@/components/game/LocalGame';
import { createSession,startRound,replaceUnillustratedRound,roundHasImages,assertSession,type Session,type Config } from '@/lib/game/engine';
import { Online } from '@/components/game/Online';
const STORAGE='demasq.local.v1';
export default function Home() {
 const [screen,setScreen]=useState<'home'|'setup'|'game'|'recap'|'online'>('home');const [session,setSession]=useState<Session|null>(null);const [editing,setEditing]=useState(false);const [modal,setModal]=useState<'rules'|'tutorial'|'settings'|'quit'|null>(null);const [error,setError]=useState('');const [loaded,setLoaded]=useState(false);
 // Hydrate device-local saved state after SSR; it cannot be read on the server.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try {const raw=localStorage.getItem(STORAGE);if(raw){const parsed:unknown=JSON.parse(raw);if(assertSession(parsed))setSession(parsed);}if(!localStorage.getItem('demasq.tutorial'))setModal('tutorial');}catch{setError('La sauvegarde locale n’a pas pu être lue. Vous pouvez commencer une nouvelle session.');}setLoaded(true);if(new URLSearchParams(location.search).has('room'))setScreen('online');},[]);
 function save(s:Session) {setSession(s);try{localStorage.setItem(STORAGE,JSON.stringify(s));}catch{setError('La sauvegarde sur cet appareil est indisponible. Gardez cet onglet ouvert.');}}
 function action(fn:()=>void){try{setError('');fn();}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.');}}
 function start(names:string[],config:Config) {action(()=>{const base=editing&&session?{...session,config}:createSession(names,config);save(!roundHasImages(base)&&base.round?.phase!=='result'?replaceUnillustratedRound(base):startRound(base));setScreen('game');setEditing(false);});}
 function closeTutorial(){setModal(null);try{localStorage.setItem('demasq.tutorial','1');}catch{}}
 return <div className="app"><header className="topbar"><button className="brand" aria-label="Accueil Démasq" onClick={()=>screen==='game'?setModal('quit'):setScreen('home')}><span className="brand-icon"><Fingerprint size={25}/></span>démasq<span className="brand-dot">.</span></button><nav><button className="nav-button" onClick={()=>setModal('rules')}><BookOpen size={18}/><span>Les règles</span></button><button className="icon-button" aria-label="Paramètres" onClick={()=>setModal('settings')}><Settings size={21}/></button></nav></header>
 <main>{error&&<div className="error" role="alert">{error}<button aria-label="Fermer l’erreur" onClick={()=>setError('')}><X size={18}/></button></div>}{screen!=='home'&&<div className="subnav"><button className="text-button" onClick={()=>screen==='game'?setModal('quit'):setScreen('home')}><ArrowLeft size={17}/>{screen==='game'?'Terminer la session':'Accueil'}</button>{screen==='game'&&<span className="pill">Manche {session?.round?.number}</span>}</div>}
 {screen==='home'&&<><div className="home-grid"><div className="home-copy"><span className="eyebrow"><span className="tiny-star">✳</span> LE JEU OÙ TOUT LE MONDE A QUELQUE CHOSE À CACHER</span><h1>Mêmes amis.<br/>Autres <span>identités.</span></h1><p className="intro">Un personnage secret. Des indices qui sèment le doute. Et parmi vous, quelqu’un qui ne voit pas les choses comme les autres.</p><div className="home-meta"><span><Users size={17}/> 3 à 12 joueurs</span><span><ShieldCheck size={17}/> Sans minuteur</span></div><div className="play-options"><button className="play-card local" onClick={()=>{setEditing(false);setScreen('setup');}}><span className="play-icon"><Smartphone size={27}/></span><span><small>TOUS ENSEMBLE</small><strong>Même téléphone</strong><span>Passez le téléphone. Gardez le secret.</span></span><span className="play-badge">JOUER</span></button><button className="play-card online" onClick={()=>setScreen('online')}><span className="play-icon"><Globe2 size={26}/></span><span><small>CHACUN SON ÉCRAN</small><strong>Jouer en ligne</strong><span>Créez un salon et retrouvez votre bande.</span></span></button></div>{loaded&&session&&<button className="resume" onClick={()=>setScreen(session.round?'game':'setup')}>Reprendre votre session · {session.players.length} joueurs · manche {session.round?.number??1}</button>}</div><div className="home-art" aria-label="Deux identités secrètes, un même univers"><div className="orbit-label"><Sparkles size={16}/> Le doute fait partie du jeu.</div><div className="sample-card back"><span className="sample-number">02 / IDENTITÉ</span><Fingerprint size={126} strokeWidth={.7}/><div><small>MÊME UNIVERS</small><strong>Autre personnage.</strong></div></div><div className="sample-card front"><span className="sample-number">01 / IDENTITÉ</span><Fingerprint size={126} strokeWidth={.7}/><div><small>TON PERSONNAGE</small><strong>Ton petit secret.</strong></div></div><div className="floating-note"><span>« Ça me paraît<br/>un peu suspect… »</span></div><div className="art-caption">LE PLUS CONVAINCANT N’A PAS TOUJOURS RAISON.</div></div></div><div className="how-strip"><div><span>01</span><p>Découvre<br/><strong>ton identité.</strong></p></div><div><span>02</span><p>Donne un indice.<br/><strong>Sème le doute.</strong></p></div><div><span>03</span><p>Vote et découvre<br/><strong>qui bluffait.</strong></p></div><button className="text-button" onClick={()=>setModal('rules')}>Le jeu en détail <BookOpen size={17}/></button></div></>}
 {screen==='setup'&&<Setup key={editing?'edit':'new'} onStart={start} initialNames={editing?session?.players.map(p=>p.name):undefined} initialConfig={editing?session?.config:undefined}/>}
 {screen==='game'&&session?.round&&<LocalGame session={session} onChange={s=>action(()=>save(s))} onReplay={()=>action(()=>save(startRound(session)))} onEdit={()=>{setEditing(true);setScreen('setup');}}/>}
 {screen==='recap'&&session&&<><Recap session={session}/><div className="actions"><button className="primary" onClick={()=>{setEditing(false);setScreen('setup');}}>Nouvelle session</button><button className="secondary" onClick={()=>setScreen('game')}>Continuer la soirée</button></div></>}
 {screen==='online'&&<Online onError={setError}/>}
 </main><footer><span>démasq. <small>Faites confiance à votre instinct. Ou pas.</small></span><button onClick={()=>setModal('rules')}>Comment jouer</button></footer>
 {modal&&<div className="modal-backdrop" onClick={()=>modal==='tutorial'?closeTutorial():setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={modal==='quit'?'Terminer la session':'Informations'} onClick={e=>e.stopPropagation()}><button autoFocus className="close icon-button" aria-label="Fermer" onClick={()=>modal==='tutorial'?closeTutorial():setModal(null)}><X/></button>{modal==='quit'?<><Trophy className="purple" size={36}/><h2>On fait les comptes ?</h2><p>Une manche en cours ne rapporte pas encore de points. Votre session reste sauvegardée sur cet appareil.</p><button className="primary wide" onClick={()=>{setScreen('recap');setModal(null);}}>Voir le récap de la session</button><button className="secondary wide" onClick={()=>setModal(null)}>Continuer à jouer</button></>:modal==='settings'?<><Settings className="purple"/><h2>Votre coin de jeu</h2><p>Le mode même téléphone est sauvegardé sur cet appareil. Le mode en ligne garde les secrets côté serveur.</p><p>Les animations respectent les réglages de mouvement réduit de votre appareil.</p><button className="secondary wide" onClick={()=>setModal('tutorial')}>Revoir le tutoriel</button></>:<><span className="eyebrow">{modal==='tutorial'?'BIENVENUE DANS LA BANDE':'LES RÈGLES'}</span><h2>Le secret est simple.<br/>Les amis, un peu moins.</h2><ol className="tutorial"><li>Regarde ton personnage en secret.</li><li>Donne un indice sans dire son nom.</li><li>Écoute les autres et repère les différences.</li><li>Vote pour celui qui te semble suspect.</li><li>Découvre le résultat et gagne des points.</li><li>Rejoue : les points restent dans la session.</li></ol>{modal==='rules'&&<div className="rules-detail"><p><strong>Deux modes.</strong> « Une autre identité » : l’imposteur reçoit un autre personnage et ignore son rôle. « Sans personnage » : il connaît son rôle et doit improviser.</p><p><strong>Victoire.</strong> Tous les imposteurs éliminés : les innocents gagnent. Autant d’imposteurs que d’innocents en jeu : les imposteurs gagnent. En cas d’égalité au vote, personne ne sort.</p><p><strong>Points.</strong> Un bon vote innocent vaut 50. Si tous les innocents encore en jeu votent pour un imposteur, chacun gagne 100 à la place. Un seul bonus par innocent et par manche, porté à 100 si nécessaire.</p><p>Chaque imposteur de l’équipe gagnante reçoit 150, ou 250 s’il n’a reçu aucun vote pendant toute la manche. Les bonus ne s’additionnent pas.</p><p>À plusieurs imposteurs, tout vote pour un imposteur encore en jeu est correct. Les éliminés ne votent plus.</p></div>}<button className="primary wide" onClick={closeTutorial}>À nous de jouer</button>{modal==='tutorial'&&<button className="text-button skip" onClick={closeTutorial}>Passer le tutoriel</button>}</>}</section></div>}
 </div>;
}
