import { useEffect,useState } from 'react';
import { Check, Eye, Fingerprint, Hand, MessageCircle, Vote, Trophy, RotateCcw, SlidersHorizontal } from 'lucide-react';
import { active,roundHasImages,markSeen,openVote,castVote,revealFor,ranking,roundTitles,type Session } from '@/lib/game/engine';
import { character } from '@/lib/game/catalog';
import { CharacterCard } from './CharacterCard';
export function Leaderboard({session,recap=false}:{session:Session;recap?:boolean}) {return <div className="leaderboard">{ranking(session).map((p,i)=><div className="leader" key={p.id}><span className="rank">{p.rank===1?'♛':p.rank}</span><span className={`avatar a${i%6}`}>{p.name.slice(0,1).toUpperCase()}</span><div className="leader-name"><strong>{p.name}</strong><small>{p.wins} victoire{p.wins>1?'s':''} · {p.played} manche{p.played>1?'s':''}{recap&&` · ${p.impostorCount} × imposteur`}</small>{recap&&<small>{p.impostorWins} victoire(s) imposteur · {p.played-p.wins} défaite(s) · {p.correctVotes}/{p.totalVotes} bons votes ({p.totalVotes?Math.round(100*p.correctVotes/p.totalVotes):0} %)</small>}{recap&&<small>{p.titles.join(' · ')||'Pas encore de distinction'}</small>}</div><div className="score"><strong>{p.points}</strong><small>{!recap&&`+${session.round?.awards[p.id]??0} cette manche`}</small></div></div>)}</div>;}
type LocalProps={session:Session;onChange:(s:Session)=>void;onReplay:()=>void;onEdit:()=>void};
export function LocalGame(props:LocalProps) {
 const r=props.session.round!;
 if(!roundHasImages(props.session)&&r.phase!=='result')return <div className="focus"><h1>Une nouvelle image, une nouvelle manche.</h1><p>Cette ancienne manche contient une identité sans image validée. Choisissez une nouvelle manche illustrée : vos joueurs, vos points acquis et votre historique restent conservés.</p><button className="primary" onClick={props.onEdit}>Choisir une manche illustrée</button></div>;
 return <LocalTurn key={`${r.number}:${r.phase}:${r.seen.length}:${r.currentVotes.length}`} {...props}/>;
}
function LocalTurn({session,onChange,onReplay,onEdit}:LocalProps) {
  const [unlocked,setUnlocked]=useState(false),[shown,setShown]=useState(false),[target,setTarget]=useState(''),[imageReady,setImageReady]=useState(false);
 const r=session.round!;const voter=active(session).find(p=>!r.currentVotes.some(v=>v.voter===p.id));const viewer=session.players.find(p=>!r.seen.includes(p.id));
 useEffect(()=>{const hide=()=>{if(document.hidden){setShown(false);setUnlocked(false);}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 const name=(id:string)=>session.players.find(p=>p.id===id)?.name??'Joueur';
 if(r.phase==='reveal'&&viewer) {const secret=revealFor(session,viewer.id);return <div className="focus"><div className="progress">{session.players.map(p=><span key={p.id} className={r.seen.includes(p.id)?'done':''}/>)}</div><span className="eyebrow">DISTRIBUTION · {r.seen.length+1} / {session.players.length}</span><h1>{unlocked?`À toi, ${viewer.name}.`:`Téléphone de ${viewer.name}`}</h1><p>{unlocked?'Garde ton identité pour toi.':'Passez-lui le téléphone, écran masqué.'}</p>{!unlocked?<><div className="sealed"><Hand size={58}/><span>À l’abri des regards</span></div><button className="primary" onClick={()=>setUnlocked(true)}>Je suis {viewer.name}</button></>:!shown?<><div className="sealed"><Fingerprint size={72}/><span>Ton identité t’attend</span></div><button className="primary" onClick={()=>{setImageReady(false);setShown(true);}}><Eye size={20}/> Voir mon personnage</button></>:<><CharacterCard id={secret.characterId} blank={secret.isBlank} onReady={setImageReady}/><button disabled={!secret.isBlank&&!imageReady} className="primary" onClick={()=>{setShown(false);setUnlocked(false);onChange(markSeen(session,viewer.id));}}><Check size={20}/> J’ai vu · masquer</button></>}<small>Ne prononce jamais le nom de ton personnage.</small></div>;}
 if(r.phase==='discussion')return <div className="focus discussion"><span className="phase-icon"><MessageCircle size={30}/></span><span className="eyebrow">MANCHE {r.number} · À VOUS DE PARLER</span><h1>Un indice.<br/><em>Pas un aveu.</em></h1>{r.ballots.length>0&&<div className="notice">{r.tied?'Égalité : personne n’est éliminé. Discutez avant de revoter.':`${name(r.lastEliminated!)} est éliminé.${session.config.revealEliminated?(r.impostors.includes(r.lastEliminated!)?' C’était un imposteur.':' C’était un innocent.'):''}`}</div>}<p>Chacun donne un indice oral, dans cet ordre.<br/>Écoutez ce qui sonne un peu… différent.</p><div className="order">{r.order.filter(id=>!r.eliminated.includes(id)).map((id,i)=><div key={id}><span className={`avatar a${i%6}`}>{i+1}</span><strong>{name(id)}</strong>{i===0&&<span className="pill">Commence</span>}</div>)}</div><button className="primary" onClick={()=>onChange(openVote(session))}><Vote size={20}/> Passer au vote</button><small>Discutez aussi longtemps que vous le souhaitez.</small></div>;
 if(r.phase==='vote'&&voter)return <div className="focus"><span className="eyebrow">VOTE SECRET · {r.currentVotes.length+1} / {active(session).length}</span><h1>{unlocked?`${voter.name}, ton verdict ?`:`Téléphone de ${voter.name}`}</h1><p>{unlocked?'Qui a une autre identité ? Tu ne peux pas voter pour toi.':'Passez le téléphone avant de choisir.'}</p>{!unlocked?<><div className="sealed"><Vote size={64}/></div><button className="primary" onClick={()=>setUnlocked(true)}>Je suis {voter.name}</button></>:<><div className="vote-options">{active(session).filter(p=>p.id!==voter.id).map((p,i)=><button className={`vote-option ${target===p.id?'selected':''}`} key={p.id} onClick={()=>setTarget(p.id)}><span className={`avatar a${i%6}`}>{p.name[0]}</span><strong>{p.name}</strong>{target===p.id&&<Check size={20}/>}</button>)}</div><button className="primary" disabled={!target} onClick={()=>{setUnlocked(false);setTarget('');onChange(castVote(session,voter.id,target));}}>Confirmer mon vote</button></>}</div>;
 return <div className="results"><div className="result-heading"><span className="phase-icon"><Trophy size={32}/></span><span className="eyebrow">MANCHE {r.number} · LE MASQUE TOMBE</span><h1>{r.winner==='innocents'?'Bien vu, les innocents !':'Quel talent de bluff !'}</h1><p>Victoire des {r.winner==='innocents'?'innocents':'imposteurs'}. Prêts à prendre votre revanche ?</p></div><div className="result-identities"><section><span className="eyebrow">LE PERSONNAGE COMMUN</span><CharacterCard id={r.main}/></section><section><span className="eyebrow">{r.impostors.map(name).join(' & ')} · IMPOSTEUR{r.impostors.length>1?'S':''}</span><CharacterCard id={session.config.mode==='blank'?null:r.alternate} blank={session.config.mode==='blank'}/></section></div><section className="panel"><div className="section-title"><Trophy/><h2>Classement de la session</h2></div><Leaderboard session={session}/></section><div className="awards">{session.players.flatMap(p=>roundTitles(session,p.id).map(t=><span className="chip" key={p.id+t}>{t} · {p.name}</span>))}</div><details className="panel"><summary>Voir les votes de la manche</summary>{r.ballots.map((b,i)=><div key={i}><h3>Vote {i+1}</h3>{b.map(v=><p key={v.voter}>{name(v.voter)} a voté pour {name(v.target)}</p>)}</div>)}</details><div className="actions"><button className="primary" onClick={onReplay}><RotateCcw size={20}/> Rejouer</button><button className="secondary" onClick={onEdit}><SlidersHorizontal size={20}/> Modifier la partie</button></div><small className="center">Les joueurs et les points restent dans la session.</small></div>;
}
export function Recap({session}:{session:Session}) {return <div className="results"><div className="result-heading"><span className="eyebrow">C’ÉTAIT UNE BELLE SOIRÉE</span><h1>Les masques tombent.<br/>Les scores restent.</h1><p>{session.players[0]?.played??0} manche(s) terminée(s)</p></div><section className="panel"><Leaderboard session={session} recap/></section><section className="panel"><h2>Vos personnages de la soirée</h2><div className="chips">{[...new Set(session.usedCharacters)].map(id=><span className="chip" key={id}>{character(id).character_name}</span>)}</div></section></div>;}
