'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Copy,Check,Eye,Users,Send,Trophy,Wifi,LogOut} from 'lucide-react';
import type {RoomView} from '@/lib/game/room';
import type {Config} from '@/lib/game/engine';
import {CharacterCard} from './CharacterCard';
import {Settings} from './Setup';
export function Online({onError}:{onError:(message:string)=>void}) {
 const [room,setRoom]=useState<RoomView|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[shown,setShown]=useState(false),[imageReady,setImageReady]=useState(false),[target,setTarget]=useState(''),[text,setText]=useState(''),[status,setStatus]=useState(''),[settings,setSettings]=useState(false),[config,setConfig]=useState<Config|null>(null),[leaving,setLeaving]=useState(false);
 const codeRef=useRef(''),inflight=useRef(false),errorRef=useRef(onError),phaseRef=useRef('');
 useEffect(()=>{errorRef.current=onError;},[onError]);
 const request=useCallback(async(type:string,extra:Record<string,unknown>={},quiet=false)=>{
  if(inflight.current)return;inflight.current=true;if(!quiet)setBusy(true);
  try{const res=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,code:codeRef.current||undefined,...extra})});const data=await res.json() as RoomView & {error?:string};if(!res.ok)throw new Error(data.error??'Connexion impossible.');
   if(type==='leave'){setRoom(null);codeRef.current='';localStorage.removeItem('demasq.room');setLeaving(false);return;}
   const phase=`${data.code}:${data.round?.number}:${data.round?.phase}`;if(phaseRef.current!==phase){setShown(false);setImageReady(false);setTarget('');phaseRef.current=phase;}
   setRoom(data);setStatus('Connecté');codeRef.current=data.code;localStorage.setItem('demasq.room',data.code);if(!quiet)errorRef.current('');
  }catch(e){const message=e instanceof Error?e.message:'Connexion interrompue.';if(quiet)setStatus('Reconnexion en cours…');else errorRef.current(message);}finally{inflight.current=false;setBusy(false);}
 },[]);
 // The saved room and invitation URL are browser-only hydration inputs.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const saved=localStorage.getItem('demasq.room');setCode(new URLSearchParams(location.search).get('room')?.toUpperCase()??'');if(saved){codeRef.current=saved;void request('heartbeat');}const timer=setInterval(()=>{if(codeRef.current&&!document.hidden)void request('heartbeat',{},true);},2500);const hide=()=>{setShown(false);if(!document.hidden&&codeRef.current)void request('heartbeat',{},true);};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hide);};},[request]);
 const send=(type:string,extra:Record<string,unknown>={})=>void request(type,extra);
 if(!room)return <div className="focus"><span className="phase-icon"><Users size={32}/></span><span className="eyebrow">CHACUN SON ÉCRAN</span><h1>La bande se retrouve.</h1><p>Créez un salon ou rejoignez vos amis avec leur code. Pour les indices, discutez ensemble ou en appel.</p><section className="panel stack"><label className="field-label">Ton pseudo<input className="field" value={name} maxLength={24} onChange={e=>setName(e.target.value)} placeholder="Comment on t’appelle ?"/></label><button className="primary" disabled={busy||!name.trim()} onClick={()=>send('create',{name})}>Créer un salon</button><div className="muted">ou rejoindre la bande</div><input aria-label="Code du salon" className="field" maxLength={6} placeholder="CODE DU SALON" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/><button className="secondary" disabled={busy||!name.trim()||code.length!==6} onClick={()=>{codeRef.current=code;send('join',{name});}}>Rejoindre</button>{busy&&<p role="status">Connexion au salon…</p>}</section><p><small>Le retour dans le salon utilise un cookie sécurisé sur ce navigateur. Aucun compte n’est nécessaire pour cette première version.</small></p></div>;
 const host=room.host===room.me,r=room.round,me=room.members.find(m=>m.id===room.me)!,pname=(id:string)=>room.members.find(m=>m.id===id)?.name??'Joueur';
 return <div className="online-layout"><div className="row" style={{justifyContent:'space-between'}}><div><span className="eyebrow">LE SALON DE {pname(room.host)}</span><div className="room-code">{room.code}</div></div><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setStatus('Lien copié !');}catch{errorRef.current(`Partagez le code ${room.code}.`);}}}><Copy size={18}/> Inviter</button></div><div className="row"><span className="status"><Wifi size={14} style={{display:'inline'}}/> {status}</span><span className="muted">{room.members.filter(m=>!m.left).length} / 12 joueurs</span></div>
 {room.lobby?<><section className="panel"><div className="section-title"><Users/><h2>Tout le monde est là ?</h2></div><div className="stack">{room.members.map((m,i)=><div className="row" key={m.id}><span className={`avatar a${i%6}`}>{m.name[0]}</span><strong>{m.name}</strong>{m.id===room.host&&<span className="pill">Hôte</span>}<span style={{marginLeft:'auto'}} className="muted">{m.left?'A quitté':!m.online?'Déconnecté':m.ready?'Prêt ✓':'Se prépare'}</span></div>)}</div></section><div className="actions"><button disabled={busy} className={me.ready?'secondary':'primary'} onClick={()=>send('ready')}><Check size={19}/>{me.ready?'Je ne suis plus prêt':'Je suis prêt'}</button>{host&&<button className="primary" disabled={busy||room.members.length<3||room.members.some(m=>!m.ready)} onClick={()=>send('start')}>Lancer la partie</button>}</div>{host&&<><button className="text-button" onClick={()=>{setConfig(room.config);setSettings(!settings);}}>Paramètres de la partie</button>{settings&&config&&<><Settings config={config} onChange={setConfig} n={Math.max(3,room.members.length)}/><label className="setting-row">Chat pendant la manche<input type="checkbox" checked={config.chat} onChange={e=>setConfig({...config,chat:e.target.checked})}/></label><button className="primary" disabled={busy} onClick={()=>{send('configure',{config});setSettings(false);}}>Enregistrer les paramètres</button></>}</>}<p className="center">{room.config.mode==='different'?'Une autre identité':'Sans personnage'} · {room.config.impostors} imposteur(s) · aucun minuteur</p></>:r&&<>
 {r.phase==='reveal'&&<div className="focus"><span className="eyebrow">MANCHE {r.number} · TON IDENTITÉ</span><h1>À toi, {me.name}.</h1>{shown?<CharacterCard id={r.secret.characterId} blank={r.secret.isBlank} onReady={setImageReady}/>:<div className="sealed"><Eye size={62}/><span>À l’abri des regards</span></div>}<button className="primary" onClick={()=>{setImageReady(false);setShown(!shown);}}>{shown?'Masquer':'Voir mon personnage'}</button>{!r.seen.includes(room.me)&&shown&&<button className="secondary wide" disabled={busy||(!r.secret.isBlank&&!imageReady)} onClick={()=>{setShown(false);send('seen');}}>J’ai vu mon personnage</button>}<p>{r.seen.length} / {room.members.length} identités consultées</p></div>}
 {r.phase==='discussion'&&<div className="focus"><span className="eyebrow">MANCHE {r.number} · LES INDICES</span><h1>Un indice.<br/><em>Pas un aveu.</em></h1>{r.ballotCount>0&&<div className="notice">{r.tied?'Égalité : personne n’est éliminé.':`${pname(r.lastEliminated!)} est éliminé.${r.eliminatedRole?' Rôle : '+(r.eliminatedRole==='impostor'?'imposteur':'innocent')+'.':''}`}</div>}<p>Parlez à tour de rôle. Prenez votre temps.</p><div className="order">{r.order.filter(id=>r.alive.includes(id)).map((id,i)=><div key={id}><span className={`avatar a${i%6}`}>{i+1}</span><strong>{pname(id)}</strong></div>)}</div>{host?<button className="primary" disabled={busy} onClick={()=>send('openVote')}>Passer au vote</button>:<p>L’hôte ouvrira le vote quand vous serez prêts.</p>}</div>}
 {r.phase==='vote'&&<div className="focus"><span className="eyebrow">VOTE SECRET</span><h1>Ton verdict ?</h1>{!r.alive.includes(room.me)?<p>Tu es éliminé. Observe les autres jouer.</p>:r.hasVoted?<div className="notice">Vote enregistré. Attendons les autres.</div>:<><div className="vote-options">{r.alive.filter(id=>id!==room.me).map(id=><button key={id} className={`vote-option ${target===id?'selected':''}`} onClick={()=>setTarget(id)}>{pname(id)}{target===id&&<Check/>}</button>)}</div><button className="primary" disabled={busy||!target} onClick={()=>send('vote',{target})}>Confirmer mon vote</button></>}<p>{r.voteCount} / {r.alive.length} votes enregistrés</p></div>}
 {r.result&&<><div className="result-heading"><span className="phase-icon"><Trophy/></span><h1>Victoire des {r.result.winner==='innocents'?'innocents':'imposteurs'} !</h1><p>Imposteur(s) : {r.result.impostors.map(pname).join(', ')}</p></div><div className="result-identities"><CharacterCard id={r.result.main}/><CharacterCard id={r.result.alternate} blank={!r.result.alternate}/></div><section className="panel"><h2>Classement de la session</h2>{[...room.players].sort((a,b)=>b.points-a.points).map(p=><div className="leader" key={p.id}><strong className="leader-name">{p.name}<small>{p.wins} victoire(s) · {p.played} manche(s)</small></strong><div className="score"><strong>{p.points}</strong><small>+{r.result!.awards[p.id]??0} cette manche</small></div></div>)}</section>{host&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>send('replay')}>Rejouer</button><button className="secondary" disabled={busy} onClick={()=>send('lobby')}>Modifier la partie</button></div>}</>}
 </>}
 {(room.lobby||room.config.chat)&&<section className="panel"><h2>Le coin discussion</h2><div className="chat-list" aria-live="polite">{!room.messages.length?<p>Aucun message. Dites bonjour à la bande.</p>:room.messages.map(m=><p key={m.id}><strong>{m.name}</strong><small>{new Date(m.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small><br/>{m.text}</p>)}</div><form className="row chat-send" onSubmit={e=>{e.preventDefault();send('message',{text});setText('');}}><input className="field" aria-label="Message" maxLength={300} value={text} placeholder="Un message pour la bande…" onChange={e=>setText(e.target.value)}/><button className="primary" aria-label="Envoyer" disabled={busy||!text.trim()}><Send size={18}/></button></form></section>}
 {leaving?<div className="notice">Quitter ce salon ? Votre place et vos points restent réservés dans cette session.<div className="actions"><button className="secondary" onClick={()=>setLeaving(false)}>Rester</button><button className="primary" disabled={busy} onClick={()=>send('leave')}>Confirmer</button></div></div>:<button className="text-button" onClick={()=>setLeaving(true)}><LogOut size={17}/> Quitter le salon</button>}</div>;
}
