import { useState } from 'react';
import { Plus, Minus, Check, Shuffle, Users, EyeOff, Search } from 'lucide-react';
import { categories,collections,playableCharacters,illustratedCharacters,characters } from '@/lib/game/catalog';
import { defaults,maxImpostors,type Config } from '@/lib/game/engine';
export function Settings({config,onChange,n}:{config:Config;onChange:(v:Config)=>void;n:number}) {
 const [query,setQuery]=useState(''); const change=(patch:Partial<Config>)=>onChange({...config,...patch});
 return <>
 <section className="panel"><div className="section-title"><span className="step">02</span><h2>Le petit twist</h2></div><div className="mode-grid">
  <button className={`choice ${config.mode==='different'?'selected':''}`} onClick={()=>change({mode:'different'})}><Users/><strong>Une autre identité</strong><span>Personne ne sait qui bluffe. Pas même l’imposteur.</span>{config.mode==='different'&&<Check className="check" size={18}/>}</button>
  <button className={`choice ${config.mode==='blank'?'selected':''}`} onClick={()=>change({mode:'blank'})}><EyeOff/><strong>Sans personnage</strong><span>L’imposteur sait qui il est. Il doit improviser.</span>{config.mode==='blank'&&<Check className="check" size={18}/>}</button>
 </div><div className="setting-row"><label htmlFor="difficulty">Difficulté des paires</label><select id="difficulty" value={config.difficulty} onChange={e=>change({difficulty:e.target.value as Config['difficulty']})}><option value="easy">Facile</option><option value="medium">Moyen</option><option value="hard">Difficile</option></select></div>
 <div className="setting-row"><label htmlFor="impostors">Imposteurs</label><select id="impostors" value={config.impostors} onChange={e=>change({impostors:Number(e.target.value)})}>{Array.from({length:Math.max(1,maxImpostors(n))},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></div>
 <label className="setting-row">Ordre aléatoire<input type="checkbox" checked={config.randomOrder} onChange={e=>change({randomOrder:e.target.checked})}/></label>
 <label className="setting-row">Révéler les rôles après élimination<input type="checkbox" checked={config.revealEliminated} onChange={e=>change({revealEliminated:e.target.checked})}/></label>
 </section>
 <section className="panel"><div className="section-title"><span className="step">03</span><h2>Votre terrain de jeu</h2></div><button className={`chip ${!config.themes.length?'active':''}`} onClick={()=>change({themes:[]})}><Shuffle size={16}/> Tout mélanger</button><label className="search"><Search size={18}/><input aria-label="Rechercher un thème" placeholder="Un univers, une série, un sport…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="chips">{[...categories,...collections].filter(t=>t.toLowerCase().includes(query.toLowerCase())).map(t=><button key={t} className={`chip ${config.themes.includes(t)?'active':''}`} onClick={()=>change({themes:config.themes.includes(t)?config.themes.filter(x=>x!==t):[...config.themes,t]})}>{t}</button>)}</div></section>
 <p className="catalog-note">{playableCharacters.length} personnages illustrés jouables. {characters.length-illustratedCharacters.length} attendent une image validée ; {illustratedCharacters.length-playableCharacters.length} attend une paire compatible. Tous restent conservés dans le catalogue.</p>
 </>;
}
export function Setup({onStart,initialNames,initialConfig}:{onStart:(names:string[],config:Config)=>void;initialNames?:string[];initialConfig?:Config}) {
 const [names,setNames]=useState(initialNames??['','','','']);const [config,setConfig]=useState(initialConfig??defaults);
 function resize(delta:number) {const next=delta>0?[...names,'']:names.slice(0,-1);setNames(next);setConfig({...config,impostors:Math.min(config.impostors,maxImpostors(next.length))});}
 return <div className="setup-grid"><div><div className="page-title"><span className="eyebrow">UN TÉLÉPHONE, TOUTE LA BANDE</span><h1>Qui joue ce soir<span> ?</span></h1><p>De 3 à 12 joueurs. Zéro compte. Autant de bluff que vous voulez.</p></div>
 <section className="panel"><div className="section-title"><span className="step">01</span><h2>La bande</h2><div className="counter"><button aria-label="Retirer un joueur" disabled={names.length<=3||!!initialNames} onClick={()=>resize(-1)}><Minus size={16}/></button><strong>{names.length}</strong><button aria-label="Ajouter un joueur" disabled={names.length>=12||!!initialNames} onClick={()=>resize(1)}><Plus size={16}/></button></div></div><div className="names">{names.map((n,i)=><label key={i}><span className={`avatar a${i%6}`}>{i+1}</span><input aria-label={`Pseudo du joueur ${i+1}`} maxLength={24} placeholder={`Joueur ${i+1}`} value={n} disabled={!!initialNames} onChange={e=>setNames(names.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div></section>
 <Settings config={config} onChange={setConfig} n={names.length}/></div><aside className="setup-summary"><span className="eyebrow">LA SOIRÉE COMMENCE ICI</span><h2>Même univers.<br/>Pas la même identité.</h2><div className="summary-icons"><span className="avatar a0">?</span><span className="avatar a2">?</span><span className="avatar a1">?</span></div><p>{names.length} joueurs · {config.impostors} imposteur{config.impostors>1?'s':''}</p><p>Donnez un indice, écoutez les autres, puis votez. Vous décidez du rythme.</p><button className="primary wide" onClick={()=>onStart(names.map((n,i)=>n.trim()||`Joueur ${i+1}`),config)}>Lancer la manche</button><small>Aucun minuteur. Aucun stress.</small></aside></div>;
}
